language: node_js
sudo: false

node_js:
  - "0.12"
  
install:
  - cd jsonrpc && npm install && cd ../client && mkdir node_modules && cd node_modules && ln -s ../../jsonrpc vscode-jsonrpc  && cd .. && npm install && cd ../server && mkdir node_modules && cd node_modules && ln -s ../../jsonrpc vscode-jsonrpc && cd .. && npm install && cd ..
  
script:
  - cd jsonrpc && npm run compile && cd ../client && npm run compile && cd ../server && npm run compile && cd ..
  - cd jsonrpc && npm test && cd ..